### ISSUE TITLE
What is the machines/ folder for?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [magnetophon/nixosConfig#4]
(Like you suggested, I'll see how far I can get without RT. But even if I never use it, I'm curious; this would help me understand Nix.)

If someone wants to ape this config, do they need to understand the machines/ folder?

I thought maybe the top-level files in this repo were for your primary machine, and the files in machines/ provide overrides for when your building on other systems, because they redefine things already defined in `commonRT.nix`, like `musnix.kernel.realtime`. But then I saw that they also define things that are nowhere defined in the top level files, like `rtirq.nameList`.

**Comment by magnetophon** [comment]
You where on the right track, but some errors in my conf threw you off:

The idea is to have everything that all my machines need in common.nix, everything that all the RT machines need in commonRT.nix and the stuff that's specific to a particular machine in the subfolders.

commonRT.nix is new, and since ATM I only have acces  to the box called thinknix, I haven't bothered removing the duplicate settings from the other boxes yet.

All clear so far?

Then inside the machine subfolders, there's two configs, that both get built at every upgrade/change:
default.nix; a setup tweaked for low battery usage
rt.nix; my RT music setup.
machine.nix has everything that is machine specific and is needed for both the rt and the default setup.

The rt goes into a separate boot-menu, so if I do nothing at boot, I get the low-battery setup. 
I'm using these aliases for that: https://github.com/magnetophon/nixosConfig/blob/master/common.nix#L840-L843

**Comment by JeffreyBenjaminBrown** [comment]
That's enormously helpful, thanks.

And  files the only ones needed for your setup? I know there are ways to mess with the default nixpkgs repo (maybe that's what overlays are?) but haven't gotten that far in the nix pills yet. Is everything else you use, uh, stock?

**Comment by magnetophon** [comment]
Yeah, 'just' the 3 repo's are needed: this one, dot and musnix.
Running on nixos-unstable.

**Comment by JeffreyBenjaminBrown** [comment]
Sorry, what do you mean by the "dot" repo?

**Comment by magnetophon** [comment]
It's not that hard to find... ;)

**Comment by JeffreyBenjaminBrown** [comment]
Ah, you mean [your own repo named .dot](https://github.com/magnetophon/.dot). I was confused because the word "dot" shows up nowhere in your config repo, so I thought you meant something like "this" or "here".

Thanks again.
